### ISSUE TITLE
code reuse can hide snooping attack

### ISSUE THREAD

**Issue by joeyh** [warner/magic-wormhole#110]
If a wormhole code can be intercepted, and used to receive a file, wormhole send --code can immediately be run by the attacker, reusing the same code to send the same file. The legitimate receiving user then receives the file they expected, via the code they expected and there is little or no indication that the data was intercepted.

I tried this attack, and was surprised to see it works. The documentation implies such attacks don't work:
> PAKE effectively trades off interaction against offline attacks. The only way for a network attacker to learn the shared key is to perform a man-in-the-middle attack during the initial connection attempt, and to correctly guess the code being used by both sides.

But with this attack, the PAKE keys are not needed; it's enough to intercept the code as it goes by on the network.

It also seems possible for the attacker to not wait to receive the whole file, in order to get their wormhole send running faster. It looks like they could stream the file they received into that send with a little work.

Note that the attacker has to supply the code to receive the file before the code can be reused. Trying to reuse the code before seems to cause receive to hang. Not sure if this is intentional, but it blocks the attack.

Could the wormhole server amelorate this attack by not letting wormhole codes be reused for say, 1 day? Might risk running out of codes or open a new DOS mechanism. But this attack seems rather bad..

**Comment by joeyh** [comment]
Of course, verification codes avoid this attack. But, much harder to use with those.

**Comment by warner** [comment]
Good point. I think this is a dup of #31, but I'm glad to have the extra consideration linked to it. My plan was to have the server put the nameplates into a "reserved" list, where they'll cool down for an hour or so before becoming eligible for a third party claim.

In general, the security of the connection is completely dependent upon the security of the wormhole code, up until the point when both legitimate sides have claimed the connection (after that point, the code can be safely revealed). So if we're talking about a threat model in which the attacker gets to know the code early, then that kind of attacker is indistinguishable from the legitimate recipient (modulo after-the-fact verification-string comparisons as you noted).

So if the code isn't kept secret until that point, an attack is pretty easy. Having the server block code re-use for some period of time makes the full man-in-the-middle attack slightly harder, but:

* the attacker is still free to mount a one-sided attack, where Alice thinks that Bob got the file (but in fact she gave it to the attacker), and Bob thinks that an error occurred
* if the attacker controls the network between the legitimate parties, they might be able to block the error message that Bob sees, or the interactive "hey, that's funny, my side says we're done, but your side says we're still waiting" conversation that would happen
* the server is still able to mount a re-use attack

which is why I haven't prioritized this change yet. I've started on a branch to address it (31-reserve-channelid), but I want to analyze the attack a bit more carefully and identify exactly what this buys us (and what sorts of attacks are still possible).

Closing this one in favor of #31.
