### ISSUE TITLE
make available all of twist and twistd's options to `wormhole-server start`

### ISSUE THREAD

**Issue by exarkun** [warner/magic-wormhole#175]
There are quite a few useful options implemented by Twisted's two command-line runners.  It would be nice to be able to use these with a wormhole server.

The current interface, `wormhole-server start`, is simpler and probably more easily approached by folks unfamiliar with Twisted.  The cost is that it's a lot less functional, too.  For example, there's no debugger integration.  There's no way to configure logging or select a reactor.

It would be quite nice if `wormhole-server start` were available in both its current form and as a plugin for twist/twistd - allowing the operator to select their preferred means of execution.

**Comment by warner** [comment]
exarkun and I talked about this a bit, and I think our plan is to:

* move the servers out to separate repos
* have those new distributions include twistd plugins (via `makeService`)
* recommend `twistd wormhole-rendezvous-server` instead of `wormhole-server start`
* add a `--shutdown-first` argument, which knows how to find the `twistd.pid`, `os.kill` it, and wait for the process to go away, before starting the new one
* recommend `twistd wormhole-rendezvous-server --shutdown-first` instead of `wormhole-server restart` (which I only ever use for testing anyways)
* recommend `twist wormhole-rendezvous-server` (note the missing D) for non-damonized environments, such as running as a systemd job
* remove the CLI command for the server entirely

I'm tempted to retain the CLI server command so there's a place to run `stop` (which would call the internal function that `--shutdown-first` uses), but that's probably not enough of a good reason to keep it. OTOH there are some diagnostic commands (list-channels, tail-usage), most of which don't currently work, but they might be nice to bring back, and they'd need an entrypoint to live on.

If we did keep the CLI command around, then `wormhole-rendezvous-server start ARGS` can delegate to `twistd.run()`, passing all the remaining arguments to it. (see my "restart-first" branch where I'm sketching this out).

**Comment by warner** [comment]
Both the rendezvous/mailbox server and the transit-relay are now implemented (in separate repos: https://github.com/warner/magic-wormhole-mailbox-server and https://github.com/warner/magic-wormhole-transit-relay) as twist/twistd plugins, so all those options are now available. `wormhole server` has been removed from the mail magic-wormhole repository.

I haven't implemented `--shutdown-first` or the `twist stop` plugin. I thought I really wanted these, but in practice I haven't needed them enough to justify the extra code. (locally I'm tending to run `twist`, which doesn't daemonize and can be killed with SIGINT, rather than start/stop/restart subcommands).

**Comment by warner** [comment]
Both daemons are now off in their own repos, so I'm going to close this one.
