### ISSUE TITLE
ImportError: cannot import name attrs

### ISSUE THREAD

**Issue by sowbug** [warner/magic-wormhole#198]
Ubuntu 16.04.2 LTS, Google Compute Engine.

> $ wormhole send it_worked.txt 
> Traceback (most recent call last):
>   File "/usr/local/bin/wormhole", line 7, in <module>
>     from wormhole.cli.cli import wormhole
>   File "/usr/local/lib/python2.7/dist-packages/wormhole/__init__.py", line 6, in <module>
>     from .wormhole import create
>   File "/usr/local/lib/python2.7/dist-packages/wormhole/wormhole.py", line 3, in <module>
>     from attr import attrs, attrib
> ImportError: cannot import name attrs

I looked up that error message on the web and didn't find anything resembling clarity. Any hints?

**Comment by sowbug** [comment]
markdown turned the _ init _ into bold.

**Comment by exarkun** [comment]
Can you provide details about how you installed the software?

**Comment by sowbug** [comment]
I followed the instructions in this repo's readme:

- `sudo apt-get -y install python-pip build-essential python-dev libffi-dev libssl-dev`
- `sudo pip install magic-wormhole`

I believe all the prereqs in the first line were already satisfied.

I then tried random permutations of `sudo pip uninstall (attr|attrs)` and probably broke things further, but the ImportError didn't change.

**Comment by meejah** [comment]
In general you shouldn't use `sudo` with `pip` -- instead create a "virtualenv" via `virtualenv venv_name` and then use `./venv_name/bin/pip install ...` etc or `source ./venv_name/bin/activate` after which invocations of `pip` in the same shell will use the virtualenv.

Can you try again in a virtualenv? Als you should run `pip install --upgrade pip setuptools` ("because Debian") in the new virtualenv as suggested in the README.

**Comment by sowbug** [comment]
I'll try it. I understand virtualenv is a best practice for isolating changes to specific development/staging/production environments; however, this particular VM instance is my random-hacking box where I don't mind semi-irreversible changes like `sudo pip`. Virtualenv will be an interesting experiment to isolate whether the problem is something unique to my instance, which is why I'm happy to try it, but long-term it shouldn't be a requirement for a tool like wormhole, which feels a lot more like something that should live in /usr/bin along with all the other userland basics.

**Comment by exarkun** [comment]
It seems most likely that the old version of pip resolved the dependencies wrong.  Hopefully creating a virtualenv with an upgraded pip will solve the problem.

Longer term, to get wormhole into /usr/bin, someone will probably make a Debian package and folks can install it that way rather than using pip.

**Comment by sowbug** [comment]
OK, the virtualenv worked. So now my promiscuous `sudo pip` ways are coming back to haunt me. Since it's a VM I can just throw it out and try again. I *think* there's nothing of value to anyone else in this bug, so might as well close as user error. I'll reopen it if I can salvage any wisdom for others. Thank you for walking through it with me.

**Comment by warner** [comment]
BTW magic-wormhole 0.9.1 is in Debian 9 ("stretch"), and Ubuntu 17.04 ("zesty"). But for older OSes, or to get a newer magic-wormhole (we're up to 0.10.2 right now), yeah you'll need `pip`.

Do you know what version of pip you were using? We could add a note to the README to recommend a minimum version.

**Comment by sowbug** [comment]
Unfortunately I updated pip after things were already screwed up, so I don't know. Today it's this:

`pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)`

So at this point, all I can contribute is that pip 9.0.1 cannot rescue an already-bad installation, but it works fine in a clean virtualenv. It looks like pip won't log its own actions unless you set it up that way, so I don't have any forensics to figure out the old version.

@warner, when I set up the new VM I'll likely go with one of those newer distros that includes the packaged tool in the repository, so thank you for those tips.

**Comment by warner** [comment]
Note to self: according to https://packages.ubuntu.com/search?keywords=python-pip&searchon=names&suite=all&section=all , ubnutu-16.04 "xenial" comes with pip-8.1.1 . The next step here is probably to test a `pip install` on a xenial VM that only contains the suggested packages (python-dev, build-essential, etc), and see what happens. If that pip is too old to figure out the full dependencies, then we should upgrade it to the next-highest-packaged-in-ubuntu one (which would be pip-8.1.2 in yakkety, or pip-9.0.1 in zesty) and see if that works. And then we should update the README with the minimum recommended version that's known to work.

(I'm assuming that pip is what's important here, and not setuptools, which may be completely wrong)

**Comment by sowbug** [comment]
I just tried with a fresh 16.04 installation. I installed the recommended prerequisites (`python-pip build-essential python-dev libffi-dev libssl-dev`) and confirmed it had pip 8.1.1. `pip install magic-wormhole` successfully installed, though pip advised at the end that I upgrade from 8.1.1. I was then able to run `wormhole send file.txt`, and it appeared to work.

**Comment by muelli** [comment]
It seems that wormhole [is depending on attrs](https://github.com/warner/magic-wormhole/blob/master/src/wormhole/wormhole.py#L3). The version seems to be at least 16.1.0, because the [Changelog](http://www.attrs.org/en/stable/changelog.html) mentions that the currently used `from attr import attrs, attrib` is only added with that version.
That fact does not seem to be encoded in setup.py which makes it hard to pip install wormhole on the current LTS Ubuntu 16.04. It seems that pip does not upgrade Ubuntu's attrs version and then the import fails:

```
File "/tmp/gks/local/lib/python2.7/site-packages/wormhole/__init__.py", line 6, in <module>
    from .wormhole import create
  File "/tmp/gks/local/lib/python2.7/site-packages/wormhole/wormhole.py", line 3, in <module>
    from attr import attrs, attrib
ImportError: cannot import name attrs
```

I would expect that mentioning `attrs >= 16.1.0` in wormhole's setup.py fixes the issue.

**Comment by warner** [comment]
`attrs` is now in setup.py, as of 68ce54ad3a99d412d4886fddc94a5f38a79777d6: that was certainly a problem. I think previously we happened to work (on most systems) because attrs is also used by one of our dependencies (I think Twisted, or maybe automat). But I think that causes problems with older versions of pip or setuptools.

I'm going to close this: I'll try to do a new release today, and I think this should be fixed in that release.

**Comment by muelli** [comment]
Nah. It's not a problem that attrs is in Wormhole's setup.py. As wormhole is indeed depending on attrs I would argue that it's a bug if attrs would not be in setup.py. The problem here, though, is that wormhole depends on attrs as of at least a certain version and that it hasn't encoded that.

**Comment by QGB** [comment]
import requests_cache
