### ISSUE TITLE
--no-fallback argument

### ISSUE THREAD

**Issue by wontonst** [warner/magic-wormhole#245]
So I heard the lightning talk at PyBay and if I understood you correctly, if you run into issues with NAT or NAT punchthrough, you fallback to a transfer server. I was thinking about implementing a `--no-fallback` argument to error out if a direct connect could not be created.

Also, on an unrelated note, as of Saturday August 12 2:15PM Pacific time, I'm getting

```
ERROR: We had a problem connecting to the relay server:
(relay URL was ws://relay.magic-wormhole.io:4000/v1)
User timeout caused connection failure.
```

I can ping `relay.magic-wormhole.io` fine.

**Comment by warner** [comment]
Interesting idea. What's the use case? It won't help with privacy, since the client still talks to the rendezvous server (and thus reveals its IP address). Although there's a `--tor` flag which will avoid that.

Thanks for the server check.. I'm not sure what was going on then. I'll try to find some cycles to set up monitoring so I can get paged if the server becomes unavailable.

**Comment by wontonst** [comment]
With some more thought I think I misunderstood the architecture at the time and the use case I had in mind is not valid.

**Comment by warner** [comment]
No worries.. thanks for the report!
