### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ManYsha** [warner/magic-wormhole#268]
When I entered wormhole receive it asked for wormhole code and I entered it .after that it says receiving file after typing 'y' ,it's showing me some errors in defer.py module and finally says permission denied: filename

**Comment by warner** [comment]
Could you paste the full output?

Is it possible that the directory you ran `wormhole receive` from was not a directory you could write to? Like you were sitting in some read-only directory?

If that's the case, maybe we should change the command to open the target file before asking for the wormhole code, to check for problems like this before consuming the code. On the other hand, we don't know what the target filename is until we've used the code and received the encrypted message from the sender (or even if we're receiving a file at all, since they might be using `wormhole send --text=MESSAGE`).

**Comment by ManYsha** [comment]
Yes ,you are right i have been trying to fetch the file from read only directory.
