### ISSUE TITLE
Send and receive commands

### ISSUE THREAD

**Issue by ManYsha** [warner/magic-wormhole#273]
In commands,
 "wormhole send ....." And 
"wormhole receive"  what is 'send' and 'receive'?.i mean, whether they are package or function name or something else.and also is wormhole.py the first module to be executed?

**Comment by warner** [comment]
We currently use the "Click" command-line argument parser (docs at http://click.pocoo.org/5/), so they're handled by Click. The first module loaded by the `wormhole` command is the `wormhole()` function in `src/wormhole/cli/cli.py` (because the `entry_points=` argument in our `setup.py` points there). `wormhole()` is a Click "group" (look around line 84, you'll see a `def wormhole(..):` that has a `@click.group()` decorator on it). Then `send` and `receive` are subcommands of that group (the `def send()` at line 196 has a `@wormhole.command()` decorator on it.

Click is handy, but kind of confusing, and it's currently a bit too strict about unicode arguments on some systems. So I'm thinking about removing Click in favor of Twisted's built-in argument-handling code. But I have other refactoring work to do first (moving the servers out to a separate package), so it's not going to happen any time soon.
