### ISSUE TITLE
Transfer of current folder "." crashes both sides of connection

### ISSUE THREAD

**Issue by mixmastamyk** [warner/magic-wormhole#275]
wormhole send .

Created a giant zipfile then waited.  Ok.

    wormhole receive 

Asked for code then crashed:

    Error: refusing to overwrite existing '.'
    TransferError: transfer rejected

This also killed the sender !  Had run send and make the (huge) zipfile again, then:

    wormhole receive -o tempfolder

Worked around the issue.  :/  

Use of the current folder "." should be handled transparently, thank you.

**Comment by gtklocker** [comment]
I was about to open an issue for how when using `wormhole send .`, the zipfile name should not be named `.` for purely aesthetic reasons, but the issue you're reporting is obviously the most serious one here.

This could be fixed by using the basename of the normpath instead of the basename of the passed argument. I suspect commit d727531e has actually fixed this already (though unknowingly),. However there hasn't been a release since 2017-09-12 so it's not included in any release. I'm supposing you're using a packaged version of `magic-wormhole` and are on version <= `0.10.3`, is that right?

Could you kindly try running from `master` and report back? This may warrant a new patch release, right @warner?

**Comment by warner** [comment]
Yeah, that sounds about right. I'll try to make a new release this weekend.. that patch has baked long enough :). Thanks for the reminder.

**Comment by mixmastamyk** [comment]
⏵ wormhole --version
    magic-wormhole 0.10.3

**Comment by warner** [comment]
Ok, 0.10.4 is out, could you test again with both ends on the new version?

**Comment by warner** [comment]
I just tested it locally, and it seems to work ok. Running `wormhole send .` from the `src/wormhole/` directory resulted in a new `wormhole/` directory on the far side, which sounds about right. Let me know if you see this problem still happening.. if not I'll close this one in a couple of days. Thanks!

**Comment by warner** [comment]
Assigning to @mixmastamyk for verification: please close (or tell me to close) if 0.10.4 works as expected.

**Comment by warner** [comment]
I haven't heard any further problem reports, so I'm assuming this is fixed. @mixmastamyk , please re-open if you see otherwise.
