### ISSUE TITLE
Slow transfer speed

### ISSUE THREAD

**Issue by deckar01** [warner/magic-wormhole#276]
I use magic-wormhole to transfer a large file between 2 computers on the same switch at **11.6MB/s**. I tested the speed between the two computers with iperf and it reported **752.8MB/s**.

There was no indication from magic-wormhole that my transfer was using a transit relay, but this speed seems to suggest that it was. How do I know if a transit relay is being used?

**Comment by warner** [comment]
Look for the line just before the progress bar. It'll show the IP address and port of the other side of the connection, an arrow to indicate whether this client made an outbound connection (`->`) or accepted an inbound one (`<-`), and `relay:` if it's using the relay:

```
Receiving (->relay:tcp:transit.magic-wormhole.io:4001)..
```

The encryption will be CPU bound, but unless you're using a small machine like a Raspberry Pi, I wouldn't expect that to be the limitation.

Note, you can force the clients to use the relay (for comparison) by using `--no-listen` on both sides, like `wormhole send --no-listen FILENAME` and `wormhole rx --no-listen`. That disables the listening socket, leaving the relay as the only remaining way to make a transfer connection.

And, depending upon your network topology, be aware that what wormhole does is to enumerate all the local IP addresses (basically it runs `ifconfig` and parses the output), and send them all (encrypted) to the other side. That could fail to establish a direct connection for any of the following reasons:

* `ifconfig` isn't installed
* it can't parse the `ifconfig` output properly (maybe yours has some new format)
* the local-interface addresses aren't actually reachable from the other peer (your network might use VLANs to isolate each port of that switch, or one of them might have a statically-assigned IP that the other one can't reach for some reason)

The connection manager just tries all the addresses it knows about and uses whichever connection is established first. I would expect that to be the fastest one, but it doesn't actually measure the speed or anything. So I could imagine a weird network in which some hard-coded port-forwarded addresses looked viable but actually required hairpin-NAT or something beyond the local switch, and for whatever reason it manages to pick that one instead of the "local" RFC1918 address.

Anyways, hopefully that'll give you enough information to investigate the problem. I know we should probably improve the `ifconfig` routine (since on linux the `ip` tool is now the preferred one, so at least we should try running that in addition to `ifconfig`). Another potential thing to improve is libsodium's `SecretBox` encryption speed, if that ends up being a limiting factor here. It's also worth experimenting with the segment size: by default we write 16KiB to the socket each time.. maybe the network is so fast (compared to the CPU) that we should raise that and see if it helps anything (I wouldn't expect it to, but you never know). Look at CHUNK_SIZE in `twisted/protocols/basic.py` in the `FileSender` class, and add something like `fs.CHUNK_SIZE = 2**20` after the `fs = basic.FileSender()` in `src/wormhole/cli/cmd_send.py` around line 375.

**Comment by warner** [comment]
@deckar01 any results?

**Comment by warner** [comment]
Not sure what we can do without more information.. hopefully the description above will be useful for future folks that want to investigate similar problems.
