### ISSUE TITLE
The Docker image no longer works

### ISSUE THREAD

**Issue by exarkun** [warner/magic-wormhole#295]
The latest images in the `magicwormhole/magic-wormhole` Dockerhub repository fail when run:

> Failed to start container with id 02aee539b422d2114ffd1e2fd3454358dee7ed22869fad058fe4614f42665068 with error: rpc error: code = 2 desc = failed to start container "02aee539b422d2114ffd1e2fd3454358dee7ed22869fad058fe4614f42665068": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/app/env/bin/wormhole-server\\\\\\\": stat /app/env/bin/wormhole-server: no such file or directory\\\"\\n\""}

This is presumably due to the removal of wormhole-server to a separate package (in 0.10.4 I think).

**Comment by warner** [comment]
Bummer.. any idea how to fix it? I know nothing about docker.

**Comment by exarkun** [comment]
Probably not very complicated, just need to put the time in.  I've been meaning to but plenty of other irons in the fire...

**Comment by warner** [comment]
From what I can tell, the Dockerfile is mostly about running a mailbox-server, and since that's been moved to `magic-wormhole-mailbox-server`, I think maybe I should just delete `Dockerfile` entirely. It might make sense to have a new Docker image here in the future for the client (do people use docker to run client-side apps?).

**Comment by taigrr** [comment]
I use docker for client side apps because it's sometimes nice to not need to install a ton of dependencies on my system, especially for me because python packages and pacman don't play very nicely together. Instead I'll just spin up docker, follow the installation instructions in there and all's (usually) good to go. Then when I uninstall it or migrate to a new machine I don't have to deal with dependency hell.

**Comment by exarkun** [comment]
The relay server has been moved to https://github.com/warner/magic-wormhole-mailbox-server (and renamed "mailbox server").  So if there is desire for a Docker image for the server, it needs to be implemented there.

**Comment by Lomanic** [comment]
The docker hub image, though massively outdated I assume, is still functional as a wormhole client with the following example
```bash
docker run -it --rm --entrypoint=/app/env/bin/wormhole -v "$PWD:/tmp/wormhole" -w /tmp/wormhole magicwormhole/magic-wormhole send filetosend.txt
```
