### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by Jonahgay** [warner/magic-wormhole#313]
during installation on a Windows 10 operating system it gives this following error:
`Command "c:\users\[NAME]\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\[NAME]\\AppData\\Local\\Temp\\pip-install-5v9s9_is\\twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\[NAME]\AppData\Local\Temp\pip-record-hkrdxptc\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\[NAME]\AppData\Local\Temp\pip-install-5v9s9_is\twisted\`

**Comment by warner** [comment]
I think we'll need some more information to diagnose this one.. did it print anything else out before that line?

What command did you use to install it?

Magic-wormhole depends upon some other Python libraries, some of which have binary components that must be compiled (and which depend upon some binary libraries being installed like libsodium), so that might be a factor.

**Comment by Jonahgay** [comment]
I seem to have solve the issue, the error was that i had to download visual c++.
But me stupid, i forgot that i posted this issue, hope i didn't cause any disturbance.
