### ISSUE TITLE
Derive link from shared secret

### ISSUE THREAD

**Issue by systemshift** [warner/magic-wormhole#324]
Currently, magic-wormhole uses a rendezvous server in order for Alice and Bob to find each other. This is a open problem with most peer-to-peer systems regarding discoverability. What makes magic-wormhole unique in this case, is that its designed with the assumption that both Alice and Bob are required to have a shared secret in order to share a file. This feature should be exploited.

What might work as a link for discoverability between Alice & Bob, is the following: hash[shared secret + UTC time]

The hash can be used as a link to find each other using a gossip protocol among open networks, such as DHT. While still retaining confidentiality in regards to shared secret.

**Comment by warner** [comment]
DHTs are great, and it'd be neat to use one in lieu of the mailbox server, but it's not trivial. See #72 for some notes.

The bigger concern is that we must not use the shared secret for anything but the PAKE protocol, because there's far too little entropy to do that safely. As an attacker, if I know there are only 65536 possible codes, then I'll just pre-compute a table that hashes all the UTC times for the next hour combined with all the possible codes (3600*65536= 236 million, might take a minute or two to generate), and then as soon as I see the link number appear on the DHT, I check my table and then I know exactly what secret code you're using. This is why the channel ID (the "4" in "4-purple-sausages") is a separate portion of the wormhole code, used only for connecting the two sides, and the secret words are only used for PAKE.

The other challenging bit is that Alice and Bob aren't starting the process at the same time. Their clocks might not be synchronized, but even if they are, Alice creates the code at one moment, and Bob types it in some number of seconds (or minutes or hours) later. Alice would have to tell Bob exactly what time her system used to generate the shared hash, which would make the code a lot larger.

Let's pick up the DHT discussion in #72.
