### ISSUE TITLE
wormhole receive x-y-z crashes for large files

### ISSUE THREAD

**Issue by morrieinmaas** [warner/magic-wormhole#327]
When sending a large file ~580MB and entering the receive code directly like:

```bash
wormhole receive 5-racketeer-music
```

wormhole crashes with:
```bash
ok? (y/N): 
transfer rejected
TransferError: transfer rejected
```
This also breaks the validity of the code so the file has to be sent again generating a new code

when manually doing:
```bash
wormhole receive
```
and entering `5-another-code` manually all works fine then.

**Comment by warner** [comment]
That sounds like the receiving side correctly negotiated the key, but then the user rejected the transfer by not typing `y` (or `Y` or `yes`) at the prompt, and yeah in the current implementation, rejecting the transfer terminates the program on both sides. This happens before the file is sent (at least when sending single files, rather than a directory). So the size of the file shouldn't matter.

Providing the code on the command line, or entering it manually/interactively, should behave exactly the same (if you type it correctly). Typing it interactively lets you use tab-completion, which might increase the chances that you get it right, but otherwise they ought to do the same thing.

Does that address the problem you saw?

**Comment by morrieinmaas** [comment]
that is correct, if I understand you correctly. An your explanation makes sense then. However, I was just surprised that it automatically assume `N` as opposed to waiting for user input. That's all fine if that's the desired/implemented behaviour. I just found that a tat counter-intuitive. 

Thanks for clarifying.

**Comment by warner** [comment]
Hm, fair point, maybe "Y" should be the default. I'll open a separate ticket for that question. Thanks!
