### ISSUE TITLE
Missing relay server should trigger error

### ISSUE THREAD

**Issue by ggeorgovassilis** [warner/magic-wormhole#355]
The setup consists of a relay server on localhost. I'm sending a file:
`wormhole --transit-helper "tcp:localhost:4001" send f4`

and receiving the file:
`wormhole --transit-helper "tcp:localhost:4002" receive 5-proximate-briefcase`

Note that I made a mistake in specifying the receiver port.

Expected behaviour: the receiver should not be able to connect to the relay server. 
Actual behaviour: the sender and receiver silently ignore the missing relay server and the transfer still happens over the public relay server.

**Comment by warner** [comment]
Are you sure the transit connection didn't just run over the local loopback interface, rather than through the (broken) relay? The code will use a direct connection if it can, and ideally only falls back to the relay if it's unable to make that work.

The line just before the progress meter will tell you the IP address it connected to, and whether that's a relay or not. When the two clients are on the same host, the loopback interface connection should be fastest, and they should show you something like:

```
Receiving (->tcp:127.0.0.1:53323)..
```

and:

```
Sending (<-127.0.0.1:53328)..
```

I also frequently see my local LAN IP address there (RFC1918), usually a 10.x or 192.168.x.x address.

The `->tcp:..` means that side initiated the TCP connection, and the `<-..` means it was listening on a TCP socket and accepted the connection.

You can force the transfer to use a relay by disabling the listening socket on both ends:

```
% wormhole send --no-listen snapcraft.yaml
Sending 1.4 kB file named 'snapcraft.yaml'
Wormhole code is: 8-bookseller-retouch
On the other computer, please run:

wormhole receive 8-bookseller-retouch

Sending (->relay:tcp:transit.magic-wormhole.io:4001)..
100%|███████████████████| 1.36k/1.36k [00:00<00:00, 4.62MB/s]
File sent.. waiting for confirmation
Confirmation received. Transfer complete.
```

and:

```
% wormhole rx --no-listen
Enter receive wormhole code: 8-bookseller-retouch
Receiving file (1.4 kB) into: snapcraft.yaml
ok? (y/N): y
Receiving (->relay:tcp:transit.magic-wormhole.io:4001)..
100%|███████████████████| 1.36k/1.36k [00:00<00:00, 7.17MB/s]
Received file written to snapcraft.yaml
```

The `->relay` lines show that both sides initiate a TCP connection to a relay.

The transit algorithm is designed to open multiple connections and use the one that completes first. It delays opening the relay connection for a moment (two seconds, look for `RELAY_DELAY` in `src/wormhole/transit.py`) so as to prioritize a direct connection.
