### ISSUE TITLE
Test fails on Python 3.8

### ISSUE THREAD

**Issue by jugmac00** [warner/magic-wormhole#366]
```
TestManager
    test_create ...                                                        [OK]
    test_follower ...                                                      [OK]
    test_leader ...                                                     [ERROR]


[ERROR]
Traceback (most recent call last):
  File "/home/jugmac00/Projects/magic-wormhole/src/wormhole/test/dilate/test_manager.py", line 248, in test_leader
    self.assertNoResult(listen_d)
  File "/home/jugmac00/Projects/magic-wormhole/.tox/py38/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 797, in assertNoResult
    deferred = ensureDeferred(deferred)
  File "/home/jugmac00/Projects/magic-wormhole/.tox/py38/lib/python3.8/site-packages/twisted/internet/defer.py", line 914, in ensureDeferred
    raise ValueError("%r is not a coroutine or a Deferred" % (coro,))
builtins.ValueError: <Mock name='mock.listen()' id='140293227258016'> is not a coroutine or a Deferred

wormhole.test.dilate.test_manager.TestManager.test_leader
-------------------------------------------------------------------------------
Ran 445 tests in 35.614s

FAILED (errors=1, successes=444)
ERROR: InvocationError for command /home/jugmac00/Projects/magic-wormhole/.tox/py38/bin/python -m wormhole.test.run_trial wormhole (exited with code 1)
________________________________________________________ summary ________________________________________________________
ERROR:   py38: commands failed
```

**Comment by warner** [comment]
I'm seeing the same failure on py2.7 and py3.7 too.. some dependency must have started behaving differently.

**Comment by warner** [comment]
reverting Twisted from 19.10.0 down to 19.7.0 makes the test pass.. something must have changed in the Endpoints code, and my mocks must have been depending upon it

Looking at the test, I don't see how it should have worked in the first place. `listen_d = m.get_endpoints().listen.listen(None)` is the troublesome line. The `EndpointRecord` (a NamedTuple that includes `.listen`) is built in the `Manager()` constructor, using the `h.listen_ep = mock.Mock()` created in `make_manager` inside `test_manager.py`. That first `.listen` should be that Mock, so I don't see why I thought calling `.listen()` on it would return a Deferred rather than the Mock.

**Comment by warner** [comment]
Ahh.. in Twisted-19.7, `self.assertNoResult(mock.Mock())` is accepted without complaint, whereas in Twisted-19.10, it throws an exception. My test was wrong before, but the old Twisted was tolerating it.
