### ISSUE TITLE
Temporary Storage in RAM

### ISSUE THREAD

**Issue by blitz** [warner/magic-wormhole#379]
When transferring directories, it seems that the temporary ZIP file is built in RAM. This is problematic, when the size of the directory exceeds available memory.

A possible solution would be to build the zip file in /tmp instead.

**Comment by warner** [comment]
Yep, for sure. This relates to #58 and #326.

**Comment by warner** [comment]
Oh, oh, ... oops.

Apparently my brain has flipped back and forth between believing this is a lingering problem (because it came up during early development), and thinking we'd solved it by switching to `SpooledTemporaryFile` so it would spill off to a tempfile on disk after it got too large. I looked back through old tickets and found [this comment](https://github.com/warner/magic-wormhole/issues/138#issuecomment-277098442) from three years ago where I explained why I assumed any remaining large-directory transfer crashes were because `/tmp` was actually a ramdisk, or it was on a small partition and filled up, or something. I think this has come up multiple times, and each time I go "oh, yeah, we should really fix that", and then I look at the code and go "oh, good, we already fixed that", and then closed the ticket.

But your report prompted me to finally run an experiment with `SpooledTemporaryFile`, and it turns out that the `max_size=` threshold, the cutoff size at which it moves everything from RAM to a temporary file on disk, *defaults to zero*, and "zero" means it never uses disk. All this time I assumed it had some reasonable default (I don't know, maybe 10 MB or so), and these crashes were because the `/tmp` directory got filled. But in fact it's never touched the disk at all, and it really is just filling RAM until it runs out.

I've been using `SpooledTemporaryFile` wrong for five years (starting with the very first release that could send directories at all, `wormhole-0.6.1`, in December 2015). Ugh.

Fortunately the fix is trivial, just give it a `max_size=` value. I'll patch that now.

Thanks @blitz for the report! I'm glad folks kept reporting this enough to overcome my stubborn belief that it was fixed :).
