### ISSUE TITLE
report initial connection failure and abort, rather than retrying forever

### ISSUE THREAD

**Issue by dkg** [warner/magic-wormhole#68]
I'd expect an attempt to use a non-responsive or non-available relay to cause "wormhole send" to fail with an error code, but instead it hangs:

```
0 dkg@alice:~$ wormhole --relay-url ws://no-such-server/v1 send  --text 'bananas'
Sending text message (7 bytes)
On the other computer, please run: wormhole receive
Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: Couldn't find the hostname 'no-such-server'.
```

I have to hit Ctrl-C to get out of this state.

**Comment by warner** [comment]
oh, good catch. I'll look into it. thanks!

**Comment by warner** [comment]
Looks like this will be addressed by my big connection-state-machine rewrite, but is kind of a hassle to fix without that. So I'm going to move it out of this milestone.

**Comment by warner** [comment]
original title was: "when server is misbehaving, "wormhole send" prints errors and then hangs rather than failing"

The general fix for this is to have the client exit-with-error if the initial connection attempt fails.

#42 (which just landed) changed the client to use a `twisted.application.internet.ClientService`, which has the awesome property that it automatically reconnects to the rendezvous server if the connection is lost (e.g. when I bounce the server host while someone's `wormhole send` is running). But it applies this same level of fierce determination to the initial connection, and in our case, it would be more useful to bail and report the error to the user, because that error is probably persistent. If the first connection fails, subsequent ones probably will too.

**Comment by warner** [comment]
We've landed the necessary changes to ClientService in Twisted today (https://github.com/twisted/twisted/commit/adbacd620d6fb58f8819ceb2a79e1d67f584c496, closing https://twistedmatrix.com/trac/ticket/9116). I've got a branch (https://github.com/warner/magic-wormhole/tree/68-first-failure) which uses this support to signal an error if the initial rendezvous-server connection fails, and all the tests there pass.

The next step is to wait for the next Twisted release (which will probably be named 17.2.0). Once that's out, we can land 68-first-failure, along with a change to our setup.py to depend upon the newer Twisted. Then we can close this.
