### ISSUE TITLE
wormhole leaks information about failed transfers

### ISSUE THREAD

**Issue by jrollins** [warner/magic-wormhole#74]
If a transfer fails on the receiver side, the sender currently sees an exception explaining what happened on the receiver side.  For instance, if the transfer failed because the receiver already had a file with the same name, the sender sees an exception (with traceback) and a message that states the receiver already had a file by that name:

```
servo:~/tmp/cdtemp.RGVnNd 0$ wormhole send foo
Sending 0 byte file named 'foo'
On the other computer, please run: wormhole receive
Wormhole code is: 3-cherokee-stormy

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wormhole/cli/cli.py", line 99, in _dispatch_command
    yield maybeDeferred(command)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
 File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_send.py", line 53, in go
    yield d
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_send.py", line 140, in _go
    % them_d["error"])
wormhole.errors.TransferError: remote error, transfer abandoned: file already exists
ERROR: remote error, transfer abandoned: file already exists`
```

Beyond the fact that it would be good if this exception was caught and presented to the user in a straightforward way, the actual exception message is an unnecessary leak of information about the state of the receiver to the sender.  Clearly the protocol has some way of reporting errors from receiver to sender.  However, I'm not sure that there is really any reason that the sender needs to know why the transfer failed, other than there was some problem on the receiver side.  As receiver, I don't necessarily want the sender to know anything about the state of my machine, such as knowing the names of files in my receiving directory.

I guess the point is that I don't think the receiver should send any information back to the sender giving any information about the state of the receivers system.  It should be sufficient just to say that the transfer failed on the receiver side, with no other context.  Sender and receiver can then communicate out-of-band about the failure if they wish.

Also, users should not ever see exception tracebacks for "normal" failure modes.  This type of failure should just print a message to the console ("transfer failed due to receiver error") and wormhole should exit with non-zero return code.

**Comment by warner** [comment]
I totally agree about hiding the traceback. We should change `src/wormhole/cli/cli.py send()` to catch `TransferError` and only display the stringified exception object.

For reference, the traceback (and the TransferError exception object itself) are entirely local: the only part that comes from the remote system is the "file already exists" string that is passed as an argument into the TransferError constructor. So the remote system is in control of how much information it reveals.

I guess I'm on the fence about whether the receiver should reveal this or not. I think it's handy, sometimes. If you search for `RespondError` in `src/wormhole/cli/cmd_receive.py`, that gives a list of all the strings that the recipient might send back in their error message:

* `unknown offer type`: probably only if the sender has a newer version, and they're sending something other than a file or directory.. this might happen some day if we handle #58 by offering a different protocol for streaming transfers
* `unknown mode`: we send a directory, and compress it with an unrecognized "zip" mode (something other than "DEFLATE").. unlikely to ever happen
* `FILENAME already exists`
* `transfer rejected` (when the receiving user says "no" to the "accept file?" prompt)

The first two are internal errors that indicate a version mismatch, and the last is clearly user-provoked.

I guess I'll agree that file-already-exists could be reported as "transfer rejected" without losing too much.. the sender's behavior is the same (re-send the file, give the recipient a new code). And really, maybe we should change the receiver code to give the recipient a chance to pick an alternative file name if the target is already present (also see #73), in which case the recipient's choice to *not* allow an alternative name would be morally equivalent to rejecting the transfer, making it more correct to report the same `transfer rejected` code for both cases.

Ok, so the action items are:

* catch `TransferError`, show it's `str()` and `sys.exit(1)` instead of allowing the exception to rise. (note: the function uses a Deferred, so it needs `d.addErrback()` and `f.trap(TransferError)` instead of the usual `try/except`)
* replace `RespondError("%s already exists")` with `RespondError("transfer rejected")` in `cmd_receive.py`
