### ISSUE TITLE
Rendezvous server

### ISSUE THREAD

**Issue by Fastidious** [warner/magic-wormhole#87]
Is there a code for this somewhere? Can the rendezvous server used by the client be changed on a configuration file?

**Comment by warner** [comment]
Sure, the rendezvous server is included in the distribution (run `wormhole-server --help` to get started). You can control which rendezvous server the client uses with a command-line argument (`--relay-url=XYZ`, where XYZ should probably be something like `ws://HOSTNAME:PORT/v1`). You can also select the "transit helper", which is the server that connects two TCP sockets together for bulk data transfer between hosts that can't make a direct connection, with `--transit-helper=tcp:HOST:PORT`. (the transit helper is also run by `wormhole-server`).

There's not yet a config file, nor is there an environment-variable override (although the latter would be pretty easy, since the `Click` argument parser we use supports it directly). What I do for offline testing is to have a little shell script named `wormhole-local`, which just runs the regular `wormhole` with `--relay-url=` and `--transit-helper=` args that point at my local testing servers.

Does a config file seem like a useful thing to add?

**Comment by warner** [comment]
I think this can be closed now.. please reopen if you need more info.

**Comment by Fastidious** [comment]
Does a config file seem like a useful thing to add?

Yes!

**Comment by Fastidious** [comment]
Was the configuration file ever added? Thanks!

**Comment by Fastidious** [comment]
@warner wanting to keep this issue dead, was the configuration file ever added? Could you share how you run the server? Is there a systemd startup script available? Thanks!
